"""
Deal Hunter Pro X — Legal Disclaimer & Safe Terminology Module

Provides approved legal disclaimer text and a terminology sanitisation utility.

All risk assessment outputs produced by Deal Hunter Pro X are informational only.
They are generated by automated statistical analysis and do not constitute legal
advice, legal determinations, accusations of wrongdoing, or definitive claims
about any listing, seller, or third party.

Compliance references:
- South African Consumer Protection Act No. 68 of 2008 (CPA)
- Protection of Personal Information Act No. 4 of 2013 (POPIA)
- Electronic Communications and Transactions Act No. 25 of 2002 (ECT Act)
- Consumer Goods and Services Ombud (CGSO) Code of Conduct
"""

import re
from typing import Optional


# ---------------------------------------------------------------------------
# Approved legal disclaimer text blocks
# ---------------------------------------------------------------------------

LEGAL_DISCLAIMERS: dict = {
    "general": (
        "Risk assessments provided by Deal Hunter Pro X are generated by automated "
        "analysis of publicly available listing information. Results are informational "
        "only and do not constitute legal advice, a definitive determination regarding "
        "any listing or seller, or an accusation of wrongdoing against any individual "
        "or business. Users are encouraged to conduct independent due diligence before "
        "completing any transaction. Deal Hunter Pro X accepts no liability for "
        "decisions made in reliance on these assessments."
    ),

    "high_risk": (
        "This listing has been assigned an elevated risk profile by our automated "
        "analysis engine based on the presence of multiple statistical risk indicators. "
        "This assessment is not a determination of wrongdoing, does not imply illegal "
        "activity, and does not constitute an accusation against any individual or "
        "business. We strongly recommend independently verifying all listing details, "
        "meeting in a safe public location, and using secure, traceable payment methods "
        "before proceeding with any transaction. If you have concerns, please report "
        "the listing using the in-app reporting tool."
    ),

    "caution": (
        "This listing contains one or more statistical risk indicators identified by "
        "our automated analysis engine. This is an informational signal only and does "
        "not constitute a legal determination or accusation. Additional verification "
        "is recommended before completing any transaction."
    ),

    "low_risk": (
        "This listing has received a low risk indicator score based on our automated "
        "analysis. This does not guarantee the legitimacy of the listing or seller. "
        "Standard due diligence applies to all transactions. Deal Hunter Pro X "
        "recommends verifying item condition in person prior to payment."
    ),

    "automated_analysis_notice": (
        "This assessment was generated automatically by the Deal Hunter Pro X Risk "
        "Assessment Engine. Automated analysis is based on statistical pattern "
        "recognition and cannot account for all relevant contextual factors. Results "
        "should be considered alongside your own judgement and independent enquiries."
    ),

    "popia_notice": (
        "Deal Hunter Pro X processes listing data in accordance with the Protection "
        "of Personal Information Act No. 4 of 2013 (POPIA). Risk assessments are "
        "derived from publicly available listing content. No personal information is "
        "shared with third parties without consent. For queries regarding your data, "
        "contact our Information Officer at privacy@dealhunterprox.co.za."
    ),

    "report_footer": (
        "Deal Hunter Pro X Risk Assessment Engine — "
        "Analysis based on statistical pattern recognition only. "
        "Not legal advice. Not a determination of wrongdoing. "
        "All assessments are informational only. "
        "In accordance with the Consumer Protection Act No. 68 of 2008 and POPIA."
    ),

    "no_buyer_protection": (
        "Deal Hunter Pro X does not offer buyer protection, escrow services, or payment "
        "guarantee programmes. Any communication claiming otherwise should be treated as "
        "an anomalous contact. Transact directly and securely using established South "
        "African payment methods."
    ),

    "seller_due_diligence": (
        "Sellers are advised to verify buyer identity before releasing goods. "
        "Ensure all electronic fund transfers (EFTs) are reflected in your bank account "
        "before completing a transaction. Deal Hunter Pro X does not verify the identity "
        "of buyers or sellers and is not responsible for the outcome of any transaction."
    ),
}


# ---------------------------------------------------------------------------
# Safe terminology mapping
# Replaces legally or reputationally sensitive terms with approved alternatives.
# ---------------------------------------------------------------------------

SAFE_TERMINOLOGY: dict = {
    # Term -> approved alternative
    "scam": "listing with elevated risk indicators",
    "scams": "listings with elevated risk indicators",
    "scammer": "seller with atypical behaviour patterns",
    "scammers": "sellers with atypical behaviour patterns",
    "fraud": "anomalous listing characteristics",
    "fraudulent": "exhibiting anomalous listing characteristics",
    "fraudster": "individual with atypical behaviour patterns",
    "fraudsters": "individuals with atypical behaviour patterns",
    "criminal": "individual with elevated risk indicators",
    "criminals": "individuals with elevated risk indicators",
    "crime": "activity with risk indicators",
    "illegal": "potentially non-compliant",
    "illegally": "in a potentially non-compliant manner",
    "fake": "unverified",
    "fakes": "unverified items",
    "stolen": "item with ownership verification concerns",
    "theft": "ownership provenance concern",
    "thief": "individual with ownership-related risk indicators",
    "counterfeit": "item with authenticity verification recommended",
    "counterfeits": "items with authenticity verification recommended",
    "lie": "unverified claim",
    "lying": "providing unverified information",
    "liar": "source of unverified information",
    "con": "listing with elevated risk indicators",
    "conman": "seller with atypical behaviour patterns",
    "swindler": "seller with atypical behaviour patterns",
    "cheat": "listing with elevated risk indicators",
    "cheater": "seller with atypical behaviour patterns",
    "dodgy": "exhibiting anomalous characteristics",
    "shady": "exhibiting atypical characteristics",
    "suspicious": "warranting additional verification",
}


# ---------------------------------------------------------------------------
# Terminology sanitisation utility
# ---------------------------------------------------------------------------

def sanitize_output(text: str, strict: bool = False) -> str:
    """
    Replace legally or reputationally sensitive terminology with approved
    safe alternatives in any output string.

    Performs whole-word, case-insensitive replacement to avoid partial matches.
    Preserves the capitalisation style of the first character of each replaced
    term (capitalised if original term was capitalised).

    Args:
        text:   The text string to sanitise.
        strict: If True, raises ValueError when an unsafe term is detected
                rather than replacing it silently. Useful in test environments.

    Returns:
        str — The sanitised text with all flagged terms replaced by their
        approved alternatives.

    Raises:
        TypeError:  If text is not a str.
        ValueError: If strict=True and an unsafe term is found.

    Example:
        >>> sanitize_output("Watch out for scammers on this platform.")
        'Watch out for sellers with atypical behaviour patterns on this platform.'
    """
    if not isinstance(text, str):
        raise TypeError(f"text must be a str, got {type(text).__name__}")

    result = text
    for unsafe_term, safe_term in SAFE_TERMINOLOGY.items():
        # Build a whole-word pattern — also handles possessive forms (term's)
        pattern = rf"\b({re.escape(unsafe_term)})(\'s|s\b|\b)"
        flags = re.IGNORECASE

        def _replacer(match: re.Match) -> str:  # noqa: ANN001
            original = match.group(0)
            # Determine if the matched term was capitalised
            if original[0].isupper():
                return safe_term[0].upper() + safe_term[1:]
            return safe_term

        if strict and re.search(pattern, result, flags):
            raise ValueError(
                f"Unsafe term detected in output: '{unsafe_term}'. "
                f"Replace with: '{safe_term}'"
            )

        result = re.sub(pattern, _replacer, result, flags=flags)

    return result


def get_disclaimer(
    risk_level: str = "general",
    include_automated_notice: bool = True,
    include_footer: bool = True,
    include_popia: bool = False,
) -> str:
    """
    Retrieve a composed disclaimer block appropriate for the given risk level.

    Args:
        risk_level:               One of 'general', 'high_risk', 'caution',
                                  'low_risk'. Falls back to 'general' if
                                  an unrecognised value is supplied.
        include_automated_notice: Whether to append the automated analysis
                                  notice paragraph. Default True.
        include_footer:           Whether to append the report footer line.
                                  Default True.
        include_popia:            Whether to append the POPIA data notice.
                                  Default False.

    Returns:
        str — Composed disclaimer text block, paragraphs separated by
        double newlines.
    """
    level_key = risk_level if risk_level in LEGAL_DISCLAIMERS else "general"
    parts = [LEGAL_DISCLAIMERS[level_key].strip()]

    if include_automated_notice:
        parts.append(LEGAL_DISCLAIMERS["automated_analysis_notice"].strip())

    if include_popia:
        parts.append(LEGAL_DISCLAIMERS["popia_notice"].strip())

    if include_footer:
        parts.append(LEGAL_DISCLAIMERS["report_footer"].strip())

    return "\n\n".join(parts)


def check_text_for_unsafe_terms(text: str) -> dict:
    """
    Audit a text string for the presence of unsafe legal terminology
    without performing any replacements.

    Useful for validating generated output before it is displayed to users.

    Args:
        text: The text to audit.

    Returns:
        dict with keys:
            is_clean        : bool — True if no unsafe terms found
            found_terms     : list of unsafe terms detected
            safe_alternatives: dict mapping each found term to its safe
                               replacement
    """
    if not isinstance(text, str):
        raise TypeError(f"text must be a str, got {type(text).__name__}")

    found: list = []
    alternatives: dict = {}

    for unsafe_term, safe_term in SAFE_TERMINOLOGY.items():
        pattern = rf"\b{re.escape(unsafe_term)}\b"
        if re.search(pattern, text, re.IGNORECASE):
            found.append(unsafe_term)
            alternatives[unsafe_term] = safe_term

    return {
        "is_clean": len(found) == 0,
        "found_terms": found,
        "safe_alternatives": alternatives,
    }


def get_safe_term(unsafe_term: str) -> Optional[str]:
    """
    Return the approved safe alternative for a given term, or None if the
    term is not in the unsafe terminology dictionary.

    Args:
        unsafe_term: The term to look up (case-insensitive).

    Returns:
        str or None — The approved safe alternative, or None if not found.
    """
    return SAFE_TERMINOLOGY.get(unsafe_term.lower())
