# Deal Hunter Pro X - Sample Data (South African Context)

SAMPLE_DEALS = [
    {
        "id": 1,
        "title": "Apple MacBook Pro 14\" M2 - 2023 Model",
        "price": 18500,
        "original_price": 32000,
        "location": "Johannesburg",
        "platform": "Marketplace",
        "category": "Electronics",
        "posted_ago": "2 hours ago",
        "safety_score": 88,
        "risk_level": "low",
        "value_score": 92,
        "scout_source": "Scout Alpha",
        "description": "Selling my MacBook Pro 14 M2, 16GB RAM, 512GB SSD. Excellent condition, used for 8 months. Comes with original box and charger. Can meet at Sandton City for handover.",
        "seller_rating": 4.8,
    },
    {
        "id": 2,
        "title": "Samsung 65\" QLED 4K Smart TV Q80C",
        "price": 9800,
        "original_price": 22000,
        "location": "Cape Town",
        "platform": "Gumtree",
        "category": "Electronics",
        "posted_ago": "4 hours ago",
        "safety_score": 75,
        "risk_level": "caution",
        "value_score": 85,
        "scout_source": "Scout Bravo",
        "description": "Samsung 65 QLED TV in great condition. Moving abroad and need to sell urgently. Priced to go quickly. Pickup from Claremont.",
        "seller_rating": 3.9,
    },
    {
        "id": 3,
        "title": "iPhone 15 Pro 256GB - Natural Titanium",
        "price": 14200,
        "original_price": 22000,
        "location": "Pretoria",
        "platform": "OLX",
        "category": "Electronics",
        "posted_ago": "1 hour ago",
        "safety_score": 91,
        "risk_level": "low",
        "value_score": 88,
        "scout_source": "Scout Charlie",
        "description": "iPhone 15 Pro 256GB, bought 6 months ago. Upgrading to 15 Pro Max. Comes with all accessories. Battery health 97%. No scratches, always used with case.",
        "seller_rating": 4.9,
    },
    {
        "id": 4,
        "title": "Toyota Fortuner 2.8 GD-6 4x4 2020",
        "price": 485000,
        "original_price": 650000,
        "location": "Johannesburg",
        "platform": "WeBuyCars",
        "category": "Vehicles",
        "posted_ago": "3 hours ago",
        "safety_score": 94,
        "risk_level": "low",
        "value_score": 90,
        "scout_source": "Scout Delta",
        "description": "2020 Toyota Fortuner 2.8 GD-6 4x4. 78,000km, full service history. One owner. Leather interior, sunroof, reverse camera. Priced for quick sale.",
        "seller_rating": 4.7,
    },
    {
        "id": 5,
        "title": "PS5 Console + 2 Controllers + 5 Games",
        "price": 6800,
        "original_price": 12500,
        "location": "Durban",
        "platform": "Marketplace",
        "category": "Gaming",
        "posted_ago": "30 mins ago",
        "safety_score": 82,
        "risk_level": "low",
        "value_score": 87,
        "scout_source": "Scout Alpha",
        "description": "PS5 disc edition with 2 DualSense controllers and 5 games including Spider-Man 2, God of War Ragnarok. All in excellent condition. Selling due to relocating.",
        "seller_rating": 4.6,
    },
    {
        "id": 6,
        "title": "DeWalt 20V Cordless Drill Set - Full Kit",
        "price": 2200,
        "original_price": 4800,
        "location": "Johannesburg",
        "platform": "Marketplace",
        "category": "Tools",
        "posted_ago": "6 hours ago",
        "safety_score": 86,
        "risk_level": "low",
        "value_score": 84,
        "scout_source": "Scout Alpha",
        "description": "DeWalt 20V MAX cordless drill/driver set with 2 batteries, charger, and full carrying case. Barely used, bought for a home renovation project that is now complete.",
        "seller_rating": 4.5,
    },
    {
        "id": 7,
        "title": "LG Double Door Fridge 617L - Platinum Silver",
        "price": 7500,
        "original_price": 18000,
        "location": "Cape Town",
        "platform": "Gumtree",
        "category": "Appliances",
        "posted_ago": "5 hours ago",
        "safety_score": 55,
        "risk_level": "caution",
        "value_score": 78,
        "scout_source": "Scout Bravo",
        "description": "LG 617L double door fridge. 2 years old, works perfectly. Moving to a smaller place. WhatsApp only please. Send EFT deposit to reserve.",
        "seller_rating": 3.2,
    },
    {
        "id": 8,
        "title": "Honda CB500F Motorbike 2022 - Low Mileage",
        "price": 62000,
        "original_price": 92000,
        "location": "Pretoria",
        "platform": "OLX",
        "category": "Vehicles",
        "posted_ago": "2 hours ago",
        "safety_score": 89,
        "risk_level": "low",
        "value_score": 91,
        "scout_source": "Scout Charlie",
        "description": "2022 Honda CB500F in excellent condition. 11,000km. Full service history. Learner friendly, great commuter. Includes helmet and jacket as bonus.",
        "seller_rating": 4.8,
    },
    {
        "id": 9,
        "title": "7-Piece Italian Leather Lounge Suite - Charcoal",
        "price": 12000,
        "original_price": 35000,
        "location": "Johannesburg",
        "platform": "Marketplace",
        "category": "Furniture",
        "posted_ago": "1 day ago",
        "safety_score": 80,
        "risk_level": "low",
        "value_score": 89,
        "scout_source": "Scout Alpha",
        "description": "Stunning 7-piece Italian leather lounge suite. 3-seater, 2-seater, and 2 single chairs. Bought from @Home 2 years ago. Pet-free home. Can assist with delivery in Joburg.",
        "seller_rating": 4.4,
    },
    {
        "id": 10,
        "title": "iPad Pro 12.9\" M2 WiFi + Cellular 256GB",
        "price": 12500,
        "original_price": 22000,
        "location": "Cape Town",
        "platform": "Marketplace",
        "category": "Electronics",
        "posted_ago": "3 hours ago",
        "safety_score": 93,
        "risk_level": "low",
        "value_score": 86,
        "scout_source": "Scout Alpha",
        "description": "iPad Pro 12.9 M2 with Apple Pencil 2nd gen and Magic Keyboard. Purchased 7 months ago from iStore. Includes original box and all accessories. No damage.",
        "seller_rating": 5.0,
    },
    {
        "id": 11,
        "title": "Volkswagen Polo Vivo 1.4 Trendline 2021",
        "price": 165000,
        "original_price": 220000,
        "location": "Durban",
        "platform": "WeBuyCars",
        "category": "Vehicles",
        "posted_ago": "4 hours ago",
        "safety_score": 92,
        "risk_level": "low",
        "value_score": 82,
        "scout_source": "Scout Delta",
        "description": "2021 VW Polo Vivo 1.4 Trendline. 42,000km, accident-free. Full service history at VW dealer. Cloth interior, aircon, radio. Priced below market for quick sale.",
        "seller_rating": 4.6,
    },
    {
        "id": 12,
        "title": "Samsung Galaxy S24 Ultra 512GB - Titanium",
        "price": 16800,
        "original_price": 26000,
        "location": "Johannesburg",
        "platform": "OLX",
        "category": "Electronics",
        "posted_ago": "45 mins ago",
        "safety_score": 40,
        "risk_level": "elevated",
        "value_score": 76,
        "scout_source": "Scout Charlie",
        "description": "S24 Ultra 512GB. Urgent sale. Contact via WhatsApp only. Payment via EFT before collection. Price is final. No time wasters.",
        "seller_rating": 2.1,
    },
    {
        "id": 13,
        "title": "King Size Sleigh Bed Frame + Mattress",
        "price": 8500,
        "original_price": 22000,
        "location": "Pretoria",
        "platform": "Gumtree",
        "category": "Furniture",
        "posted_ago": "2 days ago",
        "safety_score": 78,
        "risk_level": "low",
        "value_score": 83,
        "scout_source": "Scout Bravo",
        "description": "King size solid wood sleigh bed with Sealy Posturepedic mattress. Excellent condition. Moving into furnished apartment. Buyer to arrange collection. Sandton area.",
        "seller_rating": 4.3,
    },
    {
        "id": 14,
        "title": "Xbox Series X 1TB + Game Pass Ultimate 3 Months",
        "price": 7200,
        "original_price": 12000,
        "location": "Cape Town",
        "platform": "Marketplace",
        "category": "Gaming",
        "posted_ago": "1 hour ago",
        "safety_score": 84,
        "risk_level": "low",
        "value_score": 88,
        "scout_source": "Scout Alpha",
        "description": "Xbox Series X barely used. Comes with 3 months Game Pass Ultimate. Selling as upgrading to gaming PC. All cables and controller included.",
        "seller_rating": 4.7,
    },
    {
        "id": 15,
        "title": "Bosch Washing Machine 8kg Front Loader Serie 6",
        "price": 5800,
        "original_price": 12500,
        "location": "Johannesburg",
        "platform": "Gumtree",
        "category": "Appliances",
        "posted_ago": "8 hours ago",
        "safety_score": 85,
        "risk_level": "low",
        "value_score": 80,
        "scout_source": "Scout Bravo",
        "description": "Bosch Serie 6 8kg front loader, 2 years old. Energy efficient, quiet operation. Reason for selling: moving and new place has one built in. Collection from Fourways.",
        "seller_rating": 4.5,
    },
    {
        "id": 16,
        "title": "Makita 18V LXT Combo Kit - 5 Tools",
        "price": 3800,
        "original_price": 9500,
        "location": "Durban",
        "platform": "OLX",
        "category": "Tools",
        "posted_ago": "5 hours ago",
        "safety_score": 72,
        "risk_level": "caution",
        "value_score": 81,
        "scout_source": "Scout Charlie",
        "description": "Makita 18V combo: drill, circular saw, jigsaw, angle grinder, torch. 3 batteries included. Selling as retiring. Cash only.",
        "seller_rating": 3.8,
    },
    {
        "id": 17,
        "title": "Nike Air Jordan 1 Retro High OG - Size 10",
        "price": 2800,
        "original_price": 4500,
        "location": "Cape Town",
        "platform": "Marketplace",
        "category": "Clothing",
        "posted_ago": "3 hours ago",
        "safety_score": 88,
        "risk_level": "low",
        "value_score": 79,
        "scout_source": "Scout Alpha",
        "description": "Nike Air Jordan 1 Retro High OG Chicago, size 10. Worn twice. Box included. Authentic - receipt from Shelflife available. No lowballs.",
        "seller_rating": 4.8,
    },
    {
        "id": 18,
        "title": "Trek Marlin 7 Mountain Bike 2022 - Large",
        "price": 9500,
        "original_price": 18000,
        "location": "Pretoria",
        "platform": "Marketplace",
        "category": "Sports",
        "posted_ago": "6 hours ago",
        "safety_score": 87,
        "risk_level": "low",
        "value_score": 86,
        "scout_source": "Scout Alpha",
        "description": "Trek Marlin 7 29er MTB, Large frame, 2022. Fox fork, Shimano Deore 10-speed. Used on trails maybe 10 times. Excellent condition. Pickup from Brooklyn, Pretoria.",
        "seller_rating": 4.6,
    },
    {
        "id": 19,
        "title": "Ford Ranger 2.0 Bi-Turbo Wildtrak 2021",
        "price": 425000,
        "original_price": 580000,
        "location": "Johannesburg",
        "platform": "WeBuyCars",
        "category": "Vehicles",
        "posted_ago": "2 hours ago",
        "safety_score": 95,
        "risk_level": "low",
        "value_score": 93,
        "scout_source": "Scout Delta",
        "description": "2021 Ford Ranger Wildtrak Bi-Turbo. 65,000km, full service history. Canopy included, tow bar, reverse sensors. Immaculate condition. Test drives welcome.",
        "seller_rating": 4.9,
    },
    {
        "id": 20,
        "title": "LG C3 OLED 55\" Smart TV 2023",
        "price": 11500,
        "original_price": 22000,
        "location": "Cape Town",
        "platform": "Marketplace",
        "category": "Electronics",
        "posted_ago": "7 hours ago",
        "safety_score": 90,
        "risk_level": "low",
        "value_score": 88,
        "scout_source": "Scout Alpha",
        "description": "LG C3 55 OLED, purchased January 2024. Moving to furnished flat. Comes with original box, remote, and wall mount. 10/10 condition. Claremont pickup.",
        "seller_rating": 4.9,
    },
    {
        "id": 21,
        "title": "Herman Miller Aeron Office Chair Size B",
        "price": 8500,
        "original_price": 28000,
        "location": "Johannesburg",
        "platform": "Gumtree",
        "category": "Furniture",
        "posted_ago": "1 day ago",
        "safety_score": 82,
        "risk_level": "low",
        "value_score": 91,
        "scout_source": "Scout Bravo",
        "description": "Herman Miller Aeron Size B (medium) in graphite. Used in home office for 2 years. All adjustments work perfectly. No wear on seat or back. Rosebank, JHB.",
        "seller_rating": 4.7,
    },
    {
        "id": 22,
        "title": "PlayStation 4 Pro 1TB + 8 Games Bundle",
        "price": 3200,
        "original_price": 7500,
        "location": "Durban",
        "platform": "OLX",
        "category": "Gaming",
        "posted_ago": "4 hours ago",
        "safety_score": 25,
        "risk_level": "high",
        "value_score": 70,
        "scout_source": "Scout Charlie",
        "description": "PS4 Pro 1TB with 8 games. Contact on WhatsApp only. Will ship nationwide, payment upfront via EFT or crypto. No meetups. Serious buyers only.",
        "seller_rating": 1.8,
    },
    {
        "id": 23,
        "title": "Smeg Retro Fridge 50s Style 298L - Cream",
        "price": 12000,
        "original_price": 24000,
        "location": "Cape Town",
        "platform": "Marketplace",
        "category": "Appliances",
        "posted_ago": "10 hours ago",
        "safety_score": 93,
        "risk_level": "low",
        "value_score": 82,
        "scout_source": "Scout Alpha",
        "description": "Smeg FAB32 retro fridge in cream. Bought 18 months ago from Hirsch's. Absolutely beautiful, just changing kitchen aesthetic. Receipt and warranty still valid.",
        "seller_rating": 4.9,
    },
    {
        "id": 24,
        "title": "Canon EOS R6 Mark II + 24-105mm f/4L Lens",
        "price": 35000,
        "original_price": 58000,
        "location": "Pretoria",
        "platform": "Marketplace",
        "category": "Electronics",
        "posted_ago": "5 hours ago",
        "safety_score": 89,
        "risk_level": "low",
        "value_score": 85,
        "scout_source": "Scout Alpha",
        "description": "Canon EOS R6 Mark II body (only 12,000 actuations) with RF 24-105mm f/4L IS USM. Both in perfect condition. Switching to Sony system. Hatfield, Pretoria.",
        "seller_rating": 4.8,
    },
    {
        "id": 25,
        "title": "Titleist Irons Set AP2 714 3-PW + Extras",
        "price": 5500,
        "original_price": 12000,
        "location": "Johannesburg",
        "platform": "Gumtree",
        "category": "Sports",
        "posted_ago": "3 hours ago",
        "safety_score": 79,
        "risk_level": "low",
        "value_score": 77,
        "scout_source": "Scout Bravo",
        "description": "Titleist AP2 714 iron set, 3-PW with steel shafts. Good condition, minor bag rash. Upgrading to T100s. Includes head covers. Randburg, JHB.",
        "seller_rating": 4.3,
    },
    {
        "id": 26,
        "title": "Dyson V15 Detect Absolute Vacuum Cleaner",
        "price": 6800,
        "original_price": 14000,
        "location": "Cape Town",
        "platform": "Marketplace",
        "category": "Appliances",
        "posted_ago": "2 hours ago",
        "safety_score": 91,
        "risk_level": "low",
        "value_score": 83,
        "scout_source": "Scout Alpha",
        "description": "Dyson V15 Detect Absolute, 14 months old. All attachments included. Works perfectly. Moving abroad. Original box and receipt available. Observatory, CT.",
        "seller_rating": 4.9,
    },
    {
        "id": 27,
        "title": "Rare 1st Edition Harry Potter Complete Set",
        "price": 3500,
        "original_price": 8000,
        "location": "Johannesburg",
        "platform": "OLX",
        "category": "Books",
        "posted_ago": "1 day ago",
        "safety_score": 68,
        "risk_level": "caution",
        "value_score": 72,
        "scout_source": "Scout Charlie",
        "description": "Complete Harry Potter set, seller claims first editions. Condition varies. Interested parties WhatsApp only. Will post for extra fee. No returns.",
        "seller_rating": 3.1,
    },
    {
        "id": 28,
        "title": "Krugerrand Gold Coin 1 oz 1979 - Collector",
        "price": 42000,
        "original_price": 45000,
        "location": "Pretoria",
        "platform": "Marketplace",
        "category": "Collectibles",
        "posted_ago": "6 hours ago",
        "safety_score": 85,
        "risk_level": "low",
        "value_score": 74,
        "scout_source": "Scout Alpha",
        "description": "1979 South African Krugerrand, 1oz gold. Good condition. Will provide certificate of authenticity. Only serious collectors. Meet at ABSA branch for transaction safety.",
        "seller_rating": 4.7,
    },
]


def get_all_deals():
    """Return all sample deals."""
    return SAMPLE_DEALS


def get_deals_by_category(category: str):
    """Return deals filtered by category."""
    if category == "All":
        return SAMPLE_DEALS
    return [d for d in SAMPLE_DEALS if d["category"] == category]


def get_deals_by_location(location: str):
    """Return deals filtered by location."""
    if location == "All":
        return SAMPLE_DEALS
    return [d for d in SAMPLE_DEALS if d["location"] == location]


def get_deals_by_platform(platform: str):
    """Return deals filtered by platform."""
    if platform == "All":
        return SAMPLE_DEALS
    return [d for d in SAMPLE_DEALS if d["platform"] == platform]


def get_top_deals(n: int = 5):
    """Return top N deals sorted by value score."""
    sorted_deals = sorted(SAMPLE_DEALS, key=lambda x: x["value_score"], reverse=True)
    return sorted_deals[:n]


def get_stats():
    """Return aggregate stats for dashboard."""
    total = len(SAMPLE_DEALS)
    high_risk = sum(1 for d in SAMPLE_DEALS if d["risk_level"] in ["elevated", "high"])
    platforms = {}
    for d in SAMPLE_DEALS:
        platforms[d["platform"]] = platforms.get(d["platform"], 0) + 1
    return {
        "total_deals": total,
        "high_risk_count": high_risk,
        "platforms": platforms,
    }


CATEGORIES = [
    "Electronics", "Vehicles", "Furniture", "Tools",
    "Clothing", "Sports", "Gaming", "Appliances", "Books", "Collectibles"
]

LOCATIONS = ["Johannesburg", "Cape Town", "Durban", "Pretoria"]

PLATFORMS = ["Marketplace", "Gumtree", "OLX", "WeBuyCars"]
